### PR TITLE
Many typos and syntax fixes

### PR DESCRIPTION
**Pull request by pReya**
Changed a lot of typos. Most common errors fixed:
* Inconsequential hyphenation
* dass/das
* Syntax problems

### CODE REVIEW

**Comment by Kakifrucht** [comment]
Nice, thanks alot! I have invited you to be Collaborator, if you wish to merge yourself / commit to master.

I'm going to publish a new release with your fixes soon!

**Comment by pReya** [comment]
Thanks for the collab invitation. Glad to help. I'll try to go over all the extension translations during the next couple of weeks. Maybe wait till the end of the month until you publish a new release.

**Comment by Kakifrucht** [comment]
Should I go ahead with the release @pReya ?

**Comment by pReya** [comment]
@Kakifrucht Sorry haven't gotten around to look over the translations. Can you give me another two weeks?

**Comment by pReya** [comment]
@Kakifrucht Finally got around to commit more changes. A new release would be cool!

**Pull request merged**
