### PR TITLE
v17development/flarum-support

### PR DESCRIPTION
**Pull request by pboschma**
### Flarum Support Plugin

Hey there!

Since a few german sites use our plugin we've wanted to translate this premium plugin in German. What is a better way then directly add it here instead of our own package.

This adds the German language for [v17development/flarum-support](https://extiverse.com/extension/v17development/flarum-support)

### CODE REVIEW

**Comment by crydotsnake** [comment]
I'm here, If help is needed.

**Comment by pboschma** [comment]
> I'm here, If help is needed.

If you still find any strange issues in our language file, you may always correct it!

**Comment by crydotsnake** [comment]
Sure, i will! :).

**Comment by Kakifrucht** [comment]
Thanks, however at the current state this repository will only collect translations for bundled plugins, not third party extensions. The plan for those, as discussed in ticket #14, was to put them in their own extended language pack. I haven't gotten around to setting up a repository for it, as @luceos planned to make language packs more official and centralize them through lokalise.com, with the same setup (two language packs per language). There wasn't much development on that front lately though, so before I set up a repository now and push that to packagist maybe he could weigh in on what's the status on that front.

**Comment by luceos** [comment]
It's currently on hold Fabian. @rob006 has a similar project though, see https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate

You could hop onto that project instead, from what I've seen he's able to offer additional languages as well 👍 His system is also automated.

**Comment by pboschma** [comment]
@Kakifrucht Okay! Then we'll include the language files into our own plugin for now.

**Comment by Kakifrucht** [comment]
I will setup a new repository for third party translations in the coming days then. You can either PR there when it is setup, or I'll just copy it in if you don't mind. I don't plan to actively translate third party extensions myself, so I'm going to rely on PR's to get that going.

**Comment by Kakifrucht** [comment]
Sorry about not doing it earlier, but I have finally come around to add a new repository for third party extensions: [flarum-de-extended](https://github.com/Kakifrucht/flarum-de-extended)

Feel free to PR your translations over there @pboschma!

**Pull request closed without merging**
